name: Dependabot Auto Merge

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build the project
        run: pnpm build

  auto-merge:
    needs: dependabot
    if: github.actor == 'dependabot[bot]' && success()
    runs-on: ubuntu-latest

    steps:
      - name: Auto-merge Dependabot updates
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
